# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: feb2a0dc79568ce38bf3b43597eaa6adec934f08f7c4c4caeafd09624efb8c1114ee5a8fbe718f4bf8063732edfe1752f88ebd517740a602f08e927fd0cb7a1e

test:
  secret_key_base: ce0e7a32ca1d01630c9e34a5706434dbbd51f55ad11d9ba020f0c1e8d69ac8a454364e61cb504d3e5798a9e04f56c1e2e1e517528e0ae51b494522d6fe4135a0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
